### ISSUE TITLE
olm compile fails on OpenBSD 6.9

### ISSUE THREAD

**Issue by Xylemon** [matrix-org/purple-matrix#119]
Compiling with MATRIX_NO_E2E=y works fine on OpenBSD 6.9, but installing olm 3.2.1 from ports and trying to compile with E2E results in the following error:

>matrix-e2e.c:953:48: error: format specifies type 'long' but the argument has type 'gint64' (aka 'long long') [-Werror,-Wformat]
>                           __func__, key_algo, count);
>                                               ^~~~~
>matrix-e2e.c:1523:73: error: format specifies type 'ssize_t' (aka 'long') but the argument has type 'gint64' (aka 'long long')
>      [-Werror,-Wformat]
>        purple_debug_info("matrixprpl", "%s: Type %zd olm\n", __func__, type);
>                                                  ~~~                   ^~~~
>                                                  %lld
>2 errors generated.
>gmake: *** [Makefile.common:41: matrix-e2e.o] Error 1

Below is a properly formatted copy:

[error.txt](https://github.com/matrix-org/purple-matrix/files/7153044/error.txt)
